const icons = {
  alignBusinessObjective: "/icons/Align business objective.png",
  crmHome: "/icons/CRM Home.png",
  crmNetwork: "/icons/CRM Network.png",
  comments: "/icons/Comments.png",
  cyberSecurity: "/icons/Cyber security,Security.png",
  erpHome: "/icons/ERP Home.png",
  erpEA: "/icons/Erp EA.png",
  facilitatedLabs: "/icons/FACILITATED LABS.png",
  global: "/icons/Global.png",
  hamburger: "/icons/Hamburger.png",
  hospitalityAcademy: "/icons/Hospitality Academy.png",
  hospitalityEA: "/icons/Hospitality EA.png",
  hospitalityHome: "/icons/Hospitality Home.png",
  hospitalityManagedServices: "/icons/Hospitality Managed services.png",
  hospitalityNetwork: "/icons/Hospitality Network.png",
  hospitalitySecurity: "/icons/Hospitality Security.png",
  instructorLedTraining: "/icons/INSTRUCTER LED TRAINING.png",
  leaders: "/icons/Leaders.png",
  managedServicesAcademy: "/icons/Managed Services Academy.png",
  managedServicesHome: "/icons/Managed Services Home.png",
  managedServicesStudio: "/icons/Managed Services, Studio.png",
  managedServicesPage: "/icons/Managed Services , Managed services page.png",
  managedServicesEA: "/icons/Managed Services EA.png",
  managedServicesNetwork: "/icons/Managed Services Network.png",
  managedServicesSecurity: "/icons/Managed services, security.png",
  privateTraining: "/icons/PRIVATE TRAINING.png",
  profitMarginMaximization: "/icons/Profit Margin Maximization.png",
  selfPacedOnlineTraining: "/icons/SELF PACED ONLINE TRAINING.png",
  security: "/icons/Security.png",
  tickBox: "/icons/Tick Box.png",
  transformativeSolutions: "/icons/Transformative Solutions.png",
  alignment: "/icons/alignment (2).png",
  arrowDownSignToNavigate: "/icons/arrow-down-sign-to-navigate.png",
  calendar: "/icons/calendar.png",
  crmAcademy: "/icons/crm Academy.png",
  crmEA: "/icons/crm EA.png",
  crmManagedServices: "/icons/crm Managed Services.png",
  crmSecurity: "/icons/crm security.png",
  crmStudio: "/icons/crm studio.png",
  cyberHome: "/icons/cyber Home.png",
  cyberSecurityAcademy: "/icons/cyber-security Academy.png",
  cyberSecurityEA: "/icons/cyber-security EA.png",
  cyberSecurityManagedServices: "/icons/cyber-security Managed services.png",
  cyberSecurityNetwork: "/icons/cyber-security Network.png",
  cyberSecurityStudio: "/icons/cyber-security studio.png",
  down: "/icons/down.png",
  erpAcademy: "/icons/erp Academy.png",
  erpManagedServices: "/icons/erp Managed services.png",
  erpNetwork: "/icons/erp Network.png",
  erpSecurity: "/icons/erp security.png",
  erpStudio: "/icons/erp studio.png",
  facebook: "/icons/facebook.png",
  Facebook: "/icons/facebook-1.png",
  hospitalityStudio: "/icons/hospitality Studio.png",
  instagram: "/icons/instagram.png",
  Instagram: "/icons/instagram-1.png",
  linkedin: "/icons/linkedin.png",
  Linkedin: "/icons/linkedin-1.png",
  location: "/icons/location.png",
  mail: "/icons/mail.png",
  productivityOptimization: "/icons/productivity optimization.png",
  rightArrow: "/icons/right-arrow.png",
  search: "/icons/search.png",
  telephone: "/icons/telephone.png",
  training: "/icons/training (1).png",
  twitter: "/icons/twitter.png",
  Twitter: "/icons/twitter-1.png",
  Line: "/icons/Line.png",
  erpSpecialization: "/icons/ERP Home.png",
  consolidate: "/icons/Consolidate.png",
  Consolidate: "/icons/consolidate.svg",
  optimize: "/icons/Optimize.png",
  Optimize: "/icons/optimize.svg",
  innovate: "/icons/Innovate.png",
  Innovate: "/icons/innovate.svg",
  accelerate: "/icons/Accelerate.png",
  Accelerate: "/icons/accelerate.svg",
  CVSubmission: "/icons/CV Submission.png",
  PhoneScreening: "/icons/Phone Screening.png",
  SkillAssessment: "/icons/Skill Assessment.png",
  FinalInterview: "/icons/Final Interview.png",
  CRM: "/icons/home-crm.png",
  ERP: "/icons/home-erp.png",
  InstructerLedTraining: "/icons/InstructerLedTraining.png",
  PrivateTraining: "/icons/PrivateTraining.png",
  SelfPacedOnlineTraining: "/icons/SelfPacedOnlineTraining.png",
  FacilitatedLabs: "/icons/FacilitatedLabs.png",
  Hospitality: "/icons/Hospitality.png",
  Frugality: "/icons/Frugality.png",
};

export default icons;
